apiVersion: v1
kind: Service
metadata:
  name: {{ include "samplechart.fullname" . }}
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.target_port }}
  selector:
    app: {{ include "samplechart.name" . }}